apiVersion: apps/v1
kind: Deployment
metadata:
    name: netflix-clone
spec:
    replicas: 2
    selector:
       matchLabels:
         app: netflix-clone
    template:
       metadata:
         name: netflix-clone
         labels:
             app: netflix-clone
       spec:
           containers:
            - name: netflix-clone
              image: sai411/netflix-clone
              env:
                - name: TMDB_V3_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: api-secret
                      key: TMDB_V3_API_KEY
              ports:
                - containerPort: 80
